version: '3.1'

services:
  express:
    image: miroslawdubaj/node-alpine
    ports: 
      - "80:8080"
    volumes: 
      - ./:/usr/src/app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'mdubaj'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'example123'
  mongo:
    image: mongo
    restart: always
    volumes: 
      - /../mongodb-strzeltu-datadir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mdubaj'
      MONGO_INITDB_ROOT_PASSWORD: 'example123'
